### ISSUE TITLE
Feedback: Really good Twitter userscript in a long time 👏👌keep improving 👍 but make all features/functionality with turn on/off options :)

### ISSUE THREAD

**Issue by BD9Max** [Invertex/Twitter-AutoHD#3]
Except the HD - obviously.

One new feature could be: toggle on/off different post types in different timelines. There is such as Control Panel for Twitter but that's mainly for the frontpage and some other. 

This doesn't work anymore: https://chrome.google.com/webstore/detail/twitter-customiser/lnlejnkgobhbdidibbjnmaamnonlfnge

And another idea: option to choose the tab (timeline) where to land when loading a userprofile, such as highlights and media instead of basic - latest tweets, latest retweets and latest quote tweets :| During the time of old Twitter this kind of redirect was part of some Twitter extension - don't remember anymore which one.

There were so many good extensions then, small and bigger.

**Comment by BD9Max** [comment]
Code is large. Some people also use it with mobile browsers. Could you add options (true/false) to turn pieces of code on/off?

**Comment by Invertex** [comment]
The main part of the code that takes the most performance is processing the timeline and mutations to it to ensure features can be used. So there isn't really much to disable there. Disabling the context menu and extra buttons wouldn't affect much. What features specifically are you wanting to disable?

The default timeline on user profile is a nice option suggestion! If I am going to add many more settings then I really need to make a separate options page, which I don't really have the time for right now. But perhaps in the future.

**Comment by BD9Max** [comment]
It's a long script to process compared to other auto hd images and videos, no crop and download button, 166k size says Violentmonkey. Anyhow thank you for the script.
