### ISSUE TITLE
Images Are No Longer Visible

### ISSUE THREAD

**Issue by NuclearVacuum** [Invertex/Twitter-AutoHD#4]
https://imgur.com/a/HuBNhV1

Images are no longer visible. You can still download them as if they are there, but you can't see them unless you click and expand them.

It's been happening for a few days now. If you could look into it, that would be great. Please keep up the great work.

**Comment by Invertex** [comment]
Hi, I believe I've fixed the issue and should be fixed in version 1.31. Try upgrading and let me know, thanks!

**Comment by NuclearVacuum** [comment]
Thank you. It looks to be working again.

But it now appears that the NSFW blur is back. This is regardless of whether the 'NSFW Blur' setting is set to on or off.

https://imgur.com/a/mSXbNo3

Thank you again.

**Comment by Invertex** [comment]
Should be fixed in the newest version! Thanks

**Comment by NuclearVacuum** [comment]
Looks to be all back up and running.

Thank you once again. I can't thank you enough for this add-on. Please keep up the great work.
