### ISSUE TITLE
HD Saving Not Working

### ISSUE THREAD

**Issue by NuclearVacuum** [Invertex/Twitter-AutoHD#9]
The ability to save files in HD has stopped working. The custom dropdown menu no longer appears and the new file names are not working.

Thank you.

**Comment by Invertex** [comment]
Pushed an update. Let me know if it fixes it!

**Comment by NuclearVacuum** [comment]
Thank you for the update. Unfortunately, nothing has changed on my end.

Now that I'm looking closer, it looks like the entire HD option isn't working (despite it being on).

https://imgur.com/a/urNdJIE

**Comment by Invertex** [comment]
Your Twitter page looks different. What browser are you using? And do you have some sort of other extension running that affects Twitter?

**Comment by NuclearVacuum** [comment]
I'm using the latest version of Firefox. I don't have any add-ons that affect Twitter (other than this userscript through Tampermonkey). Nothing looks out of the ordinary for me (sorry to say).

I've disabled a few add-ons to see if they were causing this. None of them looks to be causing this (sorry to say).

**Comment by Invertex** [comment]
Ah didn't realize it wasn't working on Firefox. Should hopefully be working in the update I just pushed.

**Comment by NuclearVacuum** [comment]
It's working now. Thank you so much.
